### ISSUE TITLE
ValueError: Illegal field requested in GetField()

### ISSUE THREAD

**Issue by meneos** [danioxoli/HotSpotAnalysis_Plugin#17]
I'm trying to calculate Moran's i with Hotspot Analysis plugin and I get this error:

`2018-11-01T16:28:42     WARNING    Traceback (most recent call last):
              File "/Users/MELEIRO/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/HotSpotAnalysis_Plugin-qgis3/hotspot_analysis.py", line 572, in run
              u.append(geometry.GetField(C))
              File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/osgeo/ogr.py", line 4749, in GetField
              raise ValueError("Illegal field requested in GetField()")
             ValueError: Illegal field requested in GetField()`

The selected attribute is a field of type Real that I joint from a text delimited layer.

**Comment by meneos** [comment]
Thank you!
