### ISSUE TITLE
Error message: "TypeError: float() argument must be a string or a number, not 'Chain'"

### ISSUE THREAD

**Issue by LuchinoB** [danioxoli/HotSpotAnalysis_Plugin#18]
Hi there,

I've successfully downloaded and installed HotspotAnalysis plugin on my QGIS 3.2.3, but as soon as I launch the plugin I get this python message:

TypeError: float() argument must be a string or a number, not 'Chain' 

As I was saying, during the installation process I didn't get any error messages in both OSGeo4W Shell and QGIS... can you help me?
Thanks,

Luca

**Comment by danioxoli** [comment]
Dear Luca,

Could you please provide me with the full text of the error message (you can look for it inside the QGIS Python console).

I will try to check in deep which is the problem. Like now, it looks like an error on the input layer used.

Best,

Daniele

**Comment by LuchinoB** [comment]
Hi Daniele,
you can find the entire string below (thanks in advance!):

018-11-09T12:40:27     WARNING    Traceback (most recent call last):
              File "C:/Users/Luca-B/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HotspotAnalysis\hotspot_analysis.py", line 551, in run
              self.load_comboBox()
              File "C:/Users/Luca-B/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HotspotAnalysis\hotspot_analysis.py", line 472, in load_comboBox
              thresh = pysal.min_threshold_dist_from_shapefile(path)
              File "C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib\site-packages\pysal\weights\user.py", line 1085, in min_threshold_dist_from_shapefile
              return min_threshold_distance(points, p)
              File "C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib\site-packages\pysal\weights\util.py", line 1142, in min_threshold_distance
              kd = KDTree(data)
              File "C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib\site-packages\pysal\cg\kdtree.py", line 54, in KDTree
              return scipy.spatial.cKDTree(data, leafsize)
              File "scipy\spatial\ckdtree.pyx", line 531, in scipy.spatial.ckdtree.cKDTree.__init__ (scipy\spatial\ckdtree.cxx:5496)
              File "C:\PROGRA~1\QGIS3~1.2\apps\Python36\lib\site-packages\numpy\core\numeric.py", line 620, in ascontiguousarray
              return array(a, dtype, copy=False, order='C', ndmin=1)
             TypeError: float() argument must be a string or a number, not 'Chain'

**Comment by danioxoli** [comment]
This is definitely due to the input file you are using. Please, remind that to run the analysis you need:

1) a shapefile (no text layers can be used)
2) shapefile must be of points or polygons (no lines layer can be used)
3) the shapefile needs to have at least a numeric attribute assigned to each geometry (no attribute coming from e.g. a join operation are valid, no holes in data are handled)

Is the above describing exactly the input data you are using?

Let me know!

Daniele

**Comment by LuchinoB** [comment]
Ok, I guess I've fixed the error removing all the line-shapes uploaded in QGIS and leaving there only the point-shape: seems definetely to work now!
Thx a lot,

Luca

**Comment by LuchinoB** [comment]
One last thing: to avoid crashes I had to convert my shape SR (it was EPSG:3003) in a EPSG:4326.

**Comment by LuchinoB** [comment]
Yeah, I was wrong with coordinates, now also EPSG3003 works well!
