### ISSUE TITLE
If no output filename is specified, ".shp/output.shp" is created

### ISSUE THREAD

**Issue by kannes** [danioxoli/HotSpotAnalysis_Plugin#35]
If no output filename is specified, a directory ".shp" will be created in the directory from which QGIS was launched. Inside that directory, a Shapefile named "output" (so "output.shp", "output.dbf", ...) is created.

**Comment by danioxoli** [comment]
This is actually an unexpected behaviour.

If no output file is specified this should results in a Python error like:

> Traceback (most recent call last): File "/Users/daniele/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/HotspotAnalysis/hotspot_analysis.py", line 635, in run y, threshold1)
> File "/Users/daniele/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/HotspotAnalysis/hotspot_analysis.py", line 315, in write_file outLayer = outDataSource.CreateLayer("output", inLayer.GetSpatialRef(), inLayer.GetLayerDefn().GetGeomType())   
> AttributeError: 'NoneType' object has no attribute 'CreateLayer'

Anyway, I did not get if this is a suggestion or an issue faced during the plugin execution. In the second case, please provide more information such as your OS and both Plugin and QGIS version where you are getting this issue.

Thank you in advance

Daniele

**Comment by kannes** [comment]
It's meant as bug report, not a suggestion, sorry for not being clear :)

I tested with `ne_10m_admin_0_countries.shp`.

![image](https://user-images.githubusercontent.com/7661092/59692715-d5156c00-91e5-11e9-94dd-c57078c5cebc.png)


![image](https://user-images.githubusercontent.com/7661092/59692659-badb8e00-91e5-11e9-90d4-9978455c41aa.png)


QGIS 3.6.3
Python 3.7
Hotspot Analysis Plugin 1.0.3
Linux
