### ISSUE TITLE
ModuleNotFoundError: No module named 'shapes'

### ISSUE THREAD

**Issue by vagvaf** [danioxoli/HotSpotAnalysis_Plugin#4]
Hello, I am trying to install the plugin in ubuntu 18.04 and qgis 3.0. but I am getting the following error:

```
ModuleNotFoundError: No module named 'shapes' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/vagvaf/.local/share/QGIS/QGIS3/profiles/default/python/plugins/HotspotAnalysis/__init__.py", line 34, in classFactory
    from .hotspot_analysis import HotspotAnalysis
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/vagvaf/.local/share/QGIS/QGIS3/profiles/default/python/plugins/HotspotAnalysis/hotspot_analysis.py", line 38, in 
    import pysal
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/vagvaf/.local/lib/python3.6/site-packages/pysal/__init__.py", line 40, in 
    import pysal.cg
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/vagvaf/.local/lib/python3.6/site-packages/pysal/cg/__init__.py", line 4, in 
    from shapes import *
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'shapes'
```

I have all packages installed:

for python 2.7
```
Requirement already satisfied: pysal in /home/vagvaf/.local/lib/python2.7/site-packages
Requirement already satisfied: numpy>=1.3 in /home/vagvaf/.local/lib/python2.7/site-packages (from pysal)
Requirement already satisfied: scipy>=0.11 in /home/vagvaf/.local/lib/python2.7/site-packages (from pysal)
```

for python 3.6
```
Requirement already satisfied: pysal in /home/vagvaf/.local/lib/python3.6/site-packages
Requirement already satisfied: scipy>=0.11 in /home/vagvaf/.local/lib/python3.6/site-packages (from pysal)
Requirement already satisfied: numpy>=1.3 in /home/vagvaf/.local/lib/python3.6/site-packages (from pysal)
```
Any help would be appreciated!

**Comment by danioxoli** [comment]
Dear Vagvaf,

Did you install PySAL using the "pip3" command?

If I remember correctly, I have faced the similar issue at the first test on Ubuntu 18 with Python 3 and PySAL (v 1.13). 

Let me know if this was helpful

Daniele

**Comment by vagvaf** [comment]
I finally fixed it. Thank you for your suggestions. I installed pysal using pip3 and then also downgraded scipy-1.0.1 to scipy-0.19.1 because i was getting another type of error related to :https://issues.qgis.org/issues/16790
