### ISSUE TITLE
HotSpot Analysis_Plugin with MacOS and QGIS 3.16

### ISSUE THREAD

**Issue by dbrosi** [danioxoli/HotSpotAnalysis_Plugin#61]
Hi Everyone!

I am a very beginner coder and I am trying to install the HotSpot Analysis Plugin. I seem to be having some trouble beyond installing the correct pysal version and think it might be based on the pathname where QGIS is trying to call the python/pysal package. I went through all the steps posted on how to get the 1.4.3 version of pysal, but still with the same warning message from QGIS. Here is what my terminal says when I check what version of pysal I have:

Name: PySAL
Version: 1.14.3
Summary: A library of spatial analysis functions.
Home-page: http://pysal.org
Author: None
Author-email: None
License: BSD
Location: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages
Requires: scipy, numpy
Required-by: 

I even tried uploading the pysal file to the folder path that QGIS uses, but then just started hitting roadblocks of it not encountering other "modules" in that folder. 

I am wondering if someone can help me figure out how to get QGIS to read the right pysal location for macOS? In terminal it says that the pysal package is located under /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages and my QGIS is mapping to /Applications/QGIS.app/Contents/Resources/python. I looked at other forums where they talk about code to change the PYTHONPATH - but none of them worked and I always ended up with error messages in either terminal or QGIS console. 

Just for reference here is the error message I get and why I think that it is a problem with the pathname. 

Couldn't load plugin 'HotspotAnalysis' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'pysal.esda' 
Traceback (most recent call last):
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/deenabrosi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/HotspotAnalysis/__init__.py", line 34, in classFactory
    from .hotspot_analysis import HotspotAnalysis
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/deenabrosi/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/HotspotAnalysis/hotspot_analysis.py", line 39, in 
    from pysal.esda.getisord import *
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'pysal.esda'

Python version: 3.8.7 (default, Feb 10 2021, 09:04:08) [Clang 12.0.0 (clang-1200.0.32.29)] 
QGIS version: 3.16.4-Hannover Hannover, 81ba6c0826 

Python Path:
/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python

Any help is very much appreciated!

**Comment by danioxoli** [comment]
hello,

It looks like the Pysal version used by QGIS is not 1.14 but superior. You can check directly from the **python console of QGIS** by typing:

```
import pysal
print(pysal.__version__)
```

then:

1) If by chance you have there pysal version 2.0, you can simply uninstall the plugin and install from zip this new version of the plugin which works with pysal 2.0: https://github.com/danioxoli/HotSpotAnalysis_Plugin/archive/qgis3pysal2.zip

2) If the version of pysal is instead actually 1.14, I suggest you to try to uninstall it from the terminal by typing:

`python -m pip uninstall pysal`

and the proceed with a new installation of pysal 2.0 like:

`sudo pip3 install pysal==2.0`.


I believe the problem can be solved with option 1) as pysal 2.0 should be already present in the MacOS QGIS. 

let me know if this was useful.

best,

**Comment by dbrosi** [comment]
Thanks for the quick response! I went through all the steps that you said, but then came up with this message:

Couldn't load plugin 'HotSpotAnalysis_Plugin-qgis3pysal2' due to an error when calling its classFactory() method 
ModuleNotFoundError: No module named 'pysal.explore.esda' 

However, I took the pysal 2.0 folder (that I knew was located in /Library/Frameworks/Python.framework/Versions/3.9/lib/ python3.9/site-packages through my terminal) and copied it into the folder /Applications/QGIS.app/Contents/ Resources/python and it worked! 

So I think it was a combination of needing the new HotSpotAnalysis_Plugin that you provided me and placing it in the correct folder for QGIS to reach it.

Again, thanks for all of your help!

**Comment by samueledward1997** [comment]
I have had the same issue, but for some reason have not had any luck. I am not experienced with python, but I have used R quite a bit. After uninstalling the plugin and reinstalling it using the link you provided, I get the error 
"Couldn't load plugin 'HotSpotAnalysis_Plugin-qgis3pysal2' due to an error when calling its classFactory() method"

I then followed the code you provided above and this was the result: 
import pysal
Traceback (most recent call last):
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/pysal/__init__.py", line 3, in <module>
    from . import explore
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/pysal/explore/__init__.py", line 4, in <module>
    import pointpats
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/pointpats/__init__.py", line 4, in <module>
    from .pointpattern import PointPattern
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/pointpats/pointpattern.py", line 12, in <module>
    from matplotlib import pyplot as plt
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg/matplotlib/pyplot.py", line 36, in <module>
    import matplotlib.colorbar
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg/matplotlib/colorbar.py", line 44, in <module>
    import matplotlib.contour as contour
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg/matplotlib/contour.py", line 17, in <module>
    import matplotlib.text as text
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg/matplotlib/text.py", line 16, in <module>
    from .textpath import TextPath  # Unused, but imported by others.
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg/matplotlib/textpath.py", line 11, in <module>
    from matplotlib.mathtext import MathTextParser
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-macosx-10.13.0-x86_64.egg/matplotlib/mathtext.py", line 27, in <module>
    from PIL import Image
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg/PIL/Image.py", line 94, in <module>
    from . import _imaging as core
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: dlopen(/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg/PIL/_imaging.cpython-38-darwin.so, 2): Library not loaded: /opt/X11/lib/libxcb.1.dylib
  Referenced from: /Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.8/site-packages/Pillow-7.2.0-py3.8-macosx-10.13.0-x86_64.egg/PIL/_imaging.cpython-38-darwin.so
  Reason: image not found
print(pysal.__version__)
Traceback (most recent call last):
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
NameError: name 'pysal' is not defined
python -m pip uninstall pysal
Traceback (most recent call last):
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/code.py", line 63, in runsource
    code = self.compile(source, filename, symbol)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/codeop.py", line 178, in __call__
    return _maybe_compile(self.compiler, source, filename, symbol)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/codeop.py", line 106, in _maybe_compile
    raise err1
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/codeop.py", line 93, in _maybe_compile
    code1 = compiler(source + "\n", filename, symbol)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/codeop.py", line 143, in __call__
    codeob = compile(source, filename, symbol, self.flags, 1)
  File "<input>", line 1
    python -m pip uninstall pysal
              ^
SyntaxError: invalid syntax
sudo pip3 install pysal==2.0
Traceback (most recent call last):
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/code.py", line 63, in runsource
    code = self.compile(source, filename, symbol)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/codeop.py", line 178, in __call__
    return _maybe_compile(self.compiler, source, filename, symbol)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/codeop.py", line 106, in _maybe_compile
    raise err1
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/codeop.py", line 93, in _maybe_compile
    code1 = compiler(source + "\n", filename, symbol)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/codeop.py", line 143, in __call__
    codeob = compile(source, filename, symbol, self.flags, 1)
  File "<input>", line 1
    sudo pip3 install pysal==2.0
         ^
SyntaxError: invalid syntax


I'm very confused about what to do. I am sure the problem is with something that I am doing wrong, but I am unsure what it is. I am running this on a Mac on OS X 10.15.7 and using QGIS 13.6.5. Any help is appreciated. I was using the hotspot analysis plugin successfully about a month ago and now I am not having any luck.

**Comment by dbrosi** [comment]
Based on the issues I had with this package (and if I am reading your errors correctly), I think your problems are:

1. You did not install the correct pysal package since both of the commands to change the pysal package have an invalid syntax error. For my Mac it worked when I used this command in the terminal app: 

pip3 install pysal==2.0 

2. The pysal file that you do have is not in the right location. You need the pysal package to be in the within the python folder under the QGIS application. For my computer the pathway was: "/Applications/QGIS.app/Contents/ Resources/python", but it looks like yours might be slightly different so take that into consideration. When I was working on this, I couldn't figure out the code for terminal to get the pysal package into this folder, so I had to manually find where my terminal was placing the pysal package and place it into the python folder that I specified above under the name "pysal" for the code to run. The command below should tell you what pysal package version you have and where it is located:

pip3 show pysal

Again, I am not super well versed in code for python so there might be a much simpler way to do this than I am doing it, but it worked for me. @danioxoli, please feel free to correct me if you think anything I said above is incorrect. 

Hope this helps!

**Comment by danioxoli** [comment]
Dear all,
the manual solution proposed by @dbrosi worked also in my test. However, it is not much safe to move Py packages manually in general... 

@samueledward1997, if both the solutions proposed in the readme and the manual one fail, try out to set QGIS paths to the package folder manually to be sure that the wanted packages are within the same python env used by QGIS (see: https://gis.stackexchange.com/questions/351280/installing-python-modules-for-qgis-3-on-mac)

Best

**Comment by andrealavarello** [comment]
Hello Daniele,

I am having issues installing the plugin in Mac. I had previously installed it, and the solution proposed by @dbrosi had worked for me (after trying all the proposed solutions). However, I have recently updated QGIS and nothing is working. I get a different error message now:

Couldn't load plugin 'HotspotAnalysis' due to an error when calling its classFactory() method 

numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython mode backend) Failed in nopython mode pipeline (step: nopython frontend) No implementation of function Function(.run_quicksort at 0x1d88acb80>) found for signature: >>> run_quicksort(array(float64, 1d, A)) There are 2 candidate implementations:   - Of which 2 did not match due to:   Overload in function 'register_jitable..wrap..ov_wrap': File: numba/core/extending.py: Line 142.     With argument(s): '(array(float64, 1d, A))':   Rejected as the implementation raised a specific error:     UnsupportedError: Failed in nopython mode pipeline (step: analyzing bytecode)   Use of unsupported opcode (LOAD_ASSERTION_ERROR) found     File "Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/misc/quicksort.py", line 180:       def run_quicksort(A):                         while high - low >= SMALL_QUICKSORT:                   assert n .run_quicksort at 0x1d88acb80>) During: typing of call at /Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/np/arrayobj.py (5007) File "Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/np/arrayobj.py", line 5007:     def array_sort_impl(arr):                 # Note we clobber the return value         sort_func(arr)         ^ During: lowering "$16call_method.6 = call $14load_method.5(func=$14load_method.5, args=[], kws=(), vararg=None)" at /Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/quantecon/random/utilities.py (85) 

--
Your help would be greatly appreciated!
