### ISSUE TITLE
HotSpotAnalysis_Plugin - similar to you all i tried all of your methods and yet repeatedly receive the error below 

### ISSUE THREAD

**Issue by lizschrek** [danioxoli/HotSpotAnalysis_Plugin#68]
Couldn't load plugin 'HotspotAnalysis' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'pysal' 
Traceback (most recent call last):
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/elizabethschrekinger/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/HotspotAnalysis/__init__.py", line 34, in classFactory
    from .hotspot_analysis import HotspotAnalysis
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/elizabethschrekinger/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/HotspotAnalysis/hotspot_analysis.py", line 38, in 
    import pysal
  File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'pysal'

Python version: 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 03:02:14) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] 
QGIS version: 3.4.2-Madeira Madeira, exported 

Python Path:
/Users/elizabethschrekinger/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/leastcostpath
/Applications/QGIS3.app/Contents/MacOS/../Resources/python
/Users/elizabethschrekinger/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/elizabethschrekinger/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/SQLite3.framework/Versions/D/Python/3.6
/Users/elizabethschrekinger
/Users/elizabethschrekinger/Library/Python/3.8/lib/python/site-packages
/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Users/elizabethschrekinger/Library/Application Support/QGIS/QGIS3/profiles/default/python

**Comment by danioxoli** [comment]
Hello,

I do not have any tested installation trial for your QGIS version. You may try this workaround: https://github.com/danioxoli/HotSpotAnalysis_Plugin/issues/67#issuecomment-884704718

(before, give a try with Pysal 2 version, the pip installation was positively tested till QGIS 3.10 version)

Best
