### ISSUE TITLE
Error  classFactory()

### ISSUE THREAD

**Issue by rusmoll** [danioxoli/HotSpotAnalysis_Plugin#78]
Hi Everyone, 
I tried to install the plugin over the zip file on my Mac, however i get a traceback.
What am I doing wrong :(

umba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython mode backend) Failed in nopython mode pipeline (step: nopython frontend) No implementation of function Function(.run_quicksort at 0x1c2c1a310>) found for signature: >>> run_quicksort(array(float64, 1d, A)) There are 2 candidate implementations:       - Of which 2 did not match due to:       Overload in function 'register_jitable..wrap..ov_wrap': File: numba/core/extending.py: Line 142.         With argument(s): '(array(float64, 1d, A))':       Rejected as the implementation raised a specific error:         UnsupportedError: Failed in nopython mode pipeline (step: analyzing bytecode)       Use of unsupported opcode (LOAD_ASSERTION_ERROR) found             File "Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/misc/quicksort.py", line 180:           def run_quicksort(A):                                 while high - low >= SMALL_QUICKSORT:                       assert n .run_quicksort at 0x1c2c1a310>) During: typing of call at /Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/np/arrayobj.py (5007) File "Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/np/arrayobj.py", line 5007:     def array_sort_impl(arr):                 # Note we clobber the return value         sort_func(arr)         ^ During: lowering "$16call_method.6 = call $14load_method.5(func=$14load_method.5, args=[], kws=(), vararg=None)" at /Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/quantecon/random/utilities.py (85) 
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/ruslan.mollow/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/HotSpotAnalysis_Plugin-qgis3pysal2/__init__.py", line 34, in classFactory
    from .hotspot_analysis import HotspotAnalysis
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/ruslan.mollow/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/HotSpotAnalysis_Plugin-qgis3pysal2/hotspot_analysis.py", line 39, in 
    from pysal.explore.esda.getisord import *
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pysal/explore/__init__.py", line 2, in 
    import giddy
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/giddy/__init__.py", line 11, in 
    from . import ergodic
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/giddy/ergodic.py", line 10, in 
    import quantecon as qe
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/quantecon/__init__.py", line 15, in 
    from . import game_theory
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/quantecon/game_theory/__init__.py", line 8, in 
    from .random import (
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/quantecon/game_theory/random.py", line 10, in 
    from ..random import probvec
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/quantecon/random/__init__.py", line 17, in 
    from .utilities import probvec, sample_without_replacement, draw
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/quantecon/random/utilities.py", line 91, in 
    _probvec_parallel = guvectorize(
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/np/ufunc/decorators.py", line 179, in wrap
    guvec.add(fty)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/np/ufunc/ufuncbuilder.py", line 211, in add
    cres, args, return_type = _compile_element_wise_function(
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/np/ufunc/ufuncbuilder.py", line 143, in _compile_element_wise_function
    cres = nb_func.compile(sig, **targetoptions)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/np/ufunc/ufuncbuilder.py", line 92, in compile
    return self._compile_core(sig, flags, locals)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/np/ufunc/ufuncbuilder.py", line 124, in _compile_core
    cres = compiler.compile_extra(typingctx, targetctx,
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/compiler.py", line 603, in compile_extra
    return pipeline.compile_extra(func)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/compiler.py", line 339, in compile_extra
    return self._compile_bytecode()
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/compiler.py", line 401, in _compile_bytecode
    return self._compile_core()
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/compiler.py", line 381, in _compile_core
    raise e
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/compiler.py", line 372, in _compile_core
    pm.run(self.state)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/compiler_machinery.py", line 341, in run
    raise patched_exception
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/compiler_machinery.py", line 332, in run
    self._runPass(idx, pass_inst, state)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/compiler_machinery.py", line 291, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/compiler_machinery.py", line 264, in check
    mangled = func(compiler_state)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/typed_passes.py", line 442, in run_pass
    NativeLowering().run_pass(state)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/typed_passes.py", line 370, in run_pass
    lower.lower()
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/lowering.py", line 179, in lower
    self.lower_normal_function(self.fndesc)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/lowering.py", line 233, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/lowering.py", line 259, in lower_function_body
    self.lower_block(block)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/lowering.py", line 273, in lower_block
    self.lower_inst(inst)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/lowering.py", line 370, in lower_inst
    val = self.lower_assign(ty, inst)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/lowering.py", line 544, in lower_assign
    return self.lower_expr(ty, value)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/lowering.py", line 1070, in lower_expr
    res = self.lower_call(resty, expr)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/lowering.py", line 806, in lower_call
    res = self._lower_call_normal(fnty, expr, signature)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/lowering.py", line 1041, in _lower_call_normal
    res = impl(self.builder, argvals, self.loc)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/base.py", line 1164, in __call__
    res = self._imp(self._context, builder, self._sig, args, loc=loc)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/base.py", line 1194, in wrapper
    return fn(*args, **kwargs)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/np/arrayobj.py", line 5009, in array_sort
    return context.compile_internal(builder, array_sort_impl, sig, args)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/base.py", line 884, in compile_internal
    cres = self.compile_subroutine(builder, impl, sig, locals)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/base.py", line 869, in compile_subroutine
    cres = self._compile_subroutine_no_cache(builder, impl, sig,
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/base.py", line 840, in _compile_subroutine_no_cache
    cres = compiler.compile_internal(self.typing_context, self,
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/compiler.py", line 677, in compile_internal
    return pipeline.compile_extra(func)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/compiler.py", line 339, in compile_extra
    return self._compile_bytecode()
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/compiler.py", line 401, in _compile_bytecode
    return self._compile_core()
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/compiler.py", line 381, in _compile_core
    raise e
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/compiler.py", line 372, in _compile_core
    pm.run(self.state)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/compiler_machinery.py", line 341, in run
    raise patched_exception
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/compiler_machinery.py", line 332, in run
    self._runPass(idx, pass_inst, state)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/compiler_machinery.py", line 291, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/compiler_machinery.py", line 264, in check
    mangled = func(compiler_state)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/typed_passes.py", line 92, in run_pass
    typemap, return_type, calltypes = type_inference_stage(
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/typed_passes.py", line 70, in type_inference_stage
    infer.propagate(raise_errors=raise_errors)
  File "/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/typeinfer.py", line 994, in propagate
    raise errors[0]
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython mode backend)
Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(.run_quicksort at 0x1c2c1a310>) found for signature:
 
 >>> run_quicksort(array(float64, 1d, A))
 
There are 2 candidate implementations:
      - Of which 2 did not match due to:
      Overload in function 'register_jitable..wrap..ov_wrap': File: numba/core/extending.py: Line 142.
        With argument(s): '(array(float64, 1d, A))':
       Rejected as the implementation raised a specific error:
         UnsupportedError: Failed in nopython mode pipeline (step: analyzing bytecode)
       Use of unsupported opcode (LOAD_ASSERTION_ERROR) found
       
       File "Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/misc/quicksort.py", line 180:
           def run_quicksort(A):
               
                   while high - low >= SMALL_QUICKSORT:
                       assert n                        ^

  raised from /Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/core/byteflow.py:269

During: resolving callee type: Function(.run_quicksort at 0x1c2c1a310>)
During: typing of call at /Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/np/arrayobj.py (5007)

File "Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg/numba/np/arrayobj.py", line 5007:
    def array_sort_impl(arr):
        
        # Note we clobber the return value
        sort_func(arr)
        ^

During: lowering "$16call_method.6 = call $14load_method.5(func=$14load_method.5, args=[], kws=(), vararg=None)" at /Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/quantecon/random/utilities.py (85)

Python-Version: 3.9.5 (default, Sep 10 2021, 16:18:19) [Clang 12.0.5 (clang-1205.0.22.11)] 
QGIS-Version: 3.22.0-Białowieża Białowieża, d9022691f1

**Comment by erenefeoglh1** [comment]
I have the same issue. Did you solve this?
