### ISSUE TITLE
ValueError: numpy.ndarray size changed

### ISSUE THREAD

**Issue by Marcoortiz22** [danioxoli/HotSpotAnalysis_Plugin#79]
Hi!
After several time I finally got succes installing pysal but after that then tried to install Hotspot Analysis plugin I got the following message:

ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject 
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/marco/.local/share/QGIS/QGIS3/profiles/default/python/plugins/HotspotAnalysis/__init__.py", line 34, in classFactory
    from .hotspot_analysis import HotspotAnalysis
  File "/usr/lib/python3.10/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/marco/.local/share/QGIS/QGIS3/profiles/default/python/plugins/HotspotAnalysis/hotspot_analysis.py", line 39, in 
    from pysal.explore.esda.getisord import *
  File "/usr/lib/python3.10/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/marco/.local/lib/python3.10/site-packages/pysal/explore/__init__.py", line 1, in 
    import esda
  File "/usr/lib/python3.10/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/marco/.local/lib/python3.10/site-packages/esda/__init__.py", line 7, in 
    from . import adbscan
  File "/usr/lib/python3.10/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/marco/.local/lib/python3.10/site-packages/esda/adbscan.py", line 8, in 
    import pandas
  File "/usr/lib/python3.10/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.10/site-packages/pandas/__init__.py", line 22, in 
    from pandas.compat import is_numpy_dev as _is_numpy_dev
  File "/usr/lib/python3.10/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.10/site-packages/pandas/compat/__init__.py", line 15, in 
    from pandas.compat.numpy import (
  File "/usr/lib/python3.10/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.10/site-packages/pandas/compat/numpy/__init__.py", line 4, in 
    from pandas.util.version import Version
  File "/usr/lib/python3.10/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.10/site-packages/pandas/util/__init__.py", line 1, in 
    from pandas.util._decorators import (  # noqa:F401
  File "/usr/lib/python3.10/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.10/site-packages/pandas/util/_decorators.py", line 14, in 
    from pandas._libs.properties import cache_readonly  # noqa:F401
  File "/usr/lib/python3.10/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/lib/python3.10/site-packages/pandas/_libs/__init__.py", line 13, in 
    from pandas._libs.interval import Interval
  File "/usr/lib/python3.10/site-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

Versión de Python: 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0] 
Versión de QGIS: 3.24.0-Tisler Tisler, exported 

Ruta de Python:
/usr/share/qgis/python
/home/marco/.local/share/QGIS/QGIS3/profiles/default/python
/home/marco/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python310.zip
/usr/lib/python3.10
/usr/lib/python3.10/lib-dynload
/home/marco/.local/lib/python3.10/site-packages
/usr/lib/python3.10/site-packages
/usr/lib/python3.10/site-packages/libpysal-4.6.0-py3.10.egg
/home/marco/.local/share/QGIS/QGIS3/profiles/default/python
/home/marco/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_resource_sharing
/home/marco/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_resource_sharing/ext_libs
/home/marco/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgisgbifapi/vendor
/home/marco/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgisgbifapi/vendor

Hope you can help me.
P. S. My OS system is Manjaro Linux (KDE version)

**Comment by danioxoli** [comment]
Dear,

it seems a problem with the numpy version: https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp

Hope this would help.

Daniele
