### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'long'`

### ISSUE THREAD

**Issue by magerlin** [danioxoli/HotSpotAnalysis_Plugin#90]
Error when trying to load HotSpotAnalysis from QGIS 

QGIS version 3.30.2-'s-Hertogenbosch
python3-libpysal version 4.3.0-1
python3-pysal version 2.3.0-2

`Couldn't load plugin 'HotspotAnalysis' due to an error when calling its classFactory() method 

AttributeError: module 'numpy' has no attribute 'long' 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/MAP/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HotspotAnalysis\__init__.py", line 34, in classFactory
    from .hotspot_analysis import HotspotAnalysis
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/MAP/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HotspotAnalysis\hotspot_analysis.py", line 39, in 
    from pysal.explore.esda.getisord import *
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\pysal\explore\__init__.py", line 1, in 
    import esda
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\esda\__init__.py", line 7, in 
    from .moran import (
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\esda\moran.py", line 8, in 
    from libpysal.weights.spatial_lag import lag_spatial as slag
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\libpysal\__init__.py", line 27, in 
    from . import cg
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\libpysal\cg\__init__.py", line 11, in 
    from .alpha_shapes import *
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\libpysal\cg\alpha_shapes.py", line 14, in 
    from ..common import requires, jit, HAS_JIT
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\libpysal\common.py", line 31, in 
    from numba import jit
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\numba\__init__.py", line 18, in 
    from numba.core import types, errors
  File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\numba\core\types\__init__.py", line 108, in 
    long_ = _make_signed(np.long)
  File "C:\OSGeo4W\apps\Python39\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'long'`

**Comment by Li-Whasaka** [comment]
Hi,have you already solved the problem？

**Comment by magerlin** [comment]
No still same error
