### ISSUE TITLE
Problem with HotSpot Analysis - ImportError: cannot import name 'Local_Spatial_Pearson' from 'esda.lee' (C:\PROGRA~1\QGIS33~1.1\apps\Python312\Lib\site-packages\esda\lee.py). Did you mean: 'Spatial_Pearson'? 

### ISSUE THREAD

**Issue by mk604mk604** [danioxoli/HotSpotAnalysis_Plugin#93]
I have installed pysal and lee and esda but I am still having this error occur in QGIS 3.38. 

ImportError: cannot import name 'Local_Spatial_Pearson' from 'esda.lee' (C:\PROGRA~1\QGIS33~1.1\apps\Python312\Lib\site-packages\esda\lee.py). Did you mean: 'Spatial_Pearson'? 

Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python\qgis\utils.py", line 426, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/cleve/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HotspotAnalysis\__init__.py", line 34, in classFactory
    from .hotspot_analysis import HotspotAnalysis
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/cleve/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HotspotAnalysis\hotspot_analysis.py", line 39, in 
    from pysal.explore.esda.getisord import *
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python312\Lib\site-packages\pysal\explore\esda\__init__.py", line 16, in 
    from esda.lee import Spatial_Pearson, Local_Spatial_Pearson
ImportError: cannot import name 'Local_Spatial_Pearson' from 'esda.lee' (C:\PROGRA~1\QGIS33~1.1\apps\Python312\Lib\site-packages\esda\lee.py). Did you mean: 'Spatial_Pearson'?

**Comment by mk604mk604** [comment]
I have upgraded my pysal, however I am now getting this issue

ImportError: cannot import name 'inf' from 'scipy' (C:\PROGRA~1\QGIS33~1.1\apps\Python312\Lib\site-packages\scipy\__init__.py)

**Comment by Vyison** [comment]
i got an error too and [this solved](https://github.com/danioxoli/HotSpotAnalysis_Plugin/issues/95#issuecomment-2618771730) it for me.

don't be confused by the original error message (in the title) i had before
