### ISSUE TITLE
ImportError: cannot import name 'inf' from 'scipy' (C:\PROGRA~1\QGIS33~1.3\apps\Python312\Lib\site-packages\scipy\__init__.py)

### ISSUE THREAD

**Issue by Vyison** [danioxoli/HotSpotAnalysis_Plugin#95]
Hello,

unfortunately, I also have a problem right at the start of the plugin.
The steps from the video link and multiple installaition&deinstallation have not fixed the error. 
Unfortunately I can't say what the problem is and I can't find it.
Is it due to my installation?
The error occurs directly after installing the plugin.

Couldn't load plugin 'HotspotAnalysis' due to an error when calling its classFactory() method 

ImportError: cannot import name 'inf' from 'scipy' (C:\PROGRA~1\QGIS33~1.3\apps\Python312\Lib\site-packages\scipy\__init__.py) 

```
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.3/apps/qgis/./python\qgis\utils.py", line 426, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/sonnl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HotspotAnalysis\__init__.py", line 34, in classFactory
    from .hotspot_analysis import HotspotAnalysis
  File "C:\PROGRA~1/QGIS33~1.3/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/sonnl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HotspotAnalysis\hotspot_analysis.py", line 38, in 
    import pysal
  File "C:\PROGRA~1/QGIS33~1.3/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sonnl\AppData\Roaming\Python\Python312\site-packages\pysal\__init__.py", line 2, in 
    from . import lib
  File "C:\PROGRA~1/QGIS33~1.3/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sonnl\AppData\Roaming\Python\Python312\site-packages\pysal\lib\__init__.py", line 27, in 
    from . import cg
  File "C:\PROGRA~1/QGIS33~1.3/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sonnl\AppData\Roaming\Python\Python312\site-packages\pysal\lib\cg\__init__.py", line 7, in 
    from .kdtree import *
  File "C:\PROGRA~1/QGIS33~1.3/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sonnl\AppData\Roaming\Python\Python312\site-packages\pysal\lib\cg\kdtree.py", line 9, in 
    from scipy import inf
ImportError: cannot import name 'inf' from 'scipy' (C:\PROGRA~1\QGIS33~1.3\apps\Python312\Lib\site-packages\scipy\__init__.py)

``` 

Best regards

**Comment by Induriel** [comment]
Hi Vyison
Sadly I have no solution, but the same issue. I'm using QGIS Version 3.38.3 Grenoble, Python 3 with all packages updated.

```
2024-10-15T19:20:14     CRITICAL    Traceback (most recent call last):
              File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 426, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HotspotAnalysis\__init__.py", line 34, in classFactory
              from .hotspot_analysis import HotspotAnalysis
              File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 923, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HotspotAnalysis\hotspot_analysis.py", line 38, in 
              import pysal
              File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 923, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users\User\AppData\Roaming\Python\Python312\site-packages\pysal\__init__.py", line 2, in 
              from . import lib
              File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 923, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users\User\AppData\Roaming\Python\Python312\site-packages\pysal\lib\__init__.py", line 27, in 
              from . import cg
              File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 923, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users\User\AppData\Roaming\Python\Python312\site-packages\pysal\lib\cg\__init__.py", line 7, in 
              from .kdtree import *
              File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 923, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users\User\AppData\Roaming\Python\Python312\site-packages\pysal\lib\cg\kdtree.py", line 9, in 
              from scipy import inf
             ImportError: cannot import name 'inf' from 'scipy' (C:\OSGeo4W\apps\Python312\Lib\site-packages\scipy\__init__.py)
      
```

**Comment by danioxoli** [comment]
The issue is likely due to the fact that Scipy removed `scipy.inf` in recent versions (starting from 1.8). A possible workaround to use the current Plugin dependencies setting is to modify the PySAL script located at:

`C:\Users\<user_name>\AppData\Roaming\Python\Python312\site-packages\pysal\lib\cg\kdtree.py`

by replacing:

`from scipy import inf`

with:

`from numpy import inf`

This fix should fix the ` ImportError`

**Comment by Vyison** [comment]
> The issue is likely due to the fact that Scipy removed `scipy.inf` in recent versions (starting from 1.8). A possible workaround to use the current Plugin dependencies setting is to modify the PySAL script located at:
> 
> `C:\Users\<user_name>\AppData\Roaming\Python\Python312\site-packages\pysal\lib\cg\kdtree.py`
> 
> by replacing:
> 
> `from scipy import inf`
> 
> with:
> 
> `from numpy import inf`
> 
> This fix should fix the ` ImportError`


In the meantime, I completely reinstalled Qgis and again got an error message.
Anyway, thanks @danioxoli  - that was the solution (at least for me).

Many thanks

**Comment by Vyison** [comment]
sorry for another post.
Solved

**Comment by xtinaa2** [comment]
Hi, thanks for your work! I have tried making changes in the file you mentioned but after saving them I cannot install the plugins in QGIS because of the “Network Error”. I have specifically installed a lower version QGIS 3.20 and followed your instructions. What do you think can be the problem?

**Comment by Vyison** [comment]
> ... What do you think can be the problem?

Sorry for my late reply. I would recommend installing ‘everything’ via OSGeo4W Setup.
Unfortunately, I'm not an expert in this area either. Since I started installing ‘Libs’ via OSGeo4W Setup, it has been running better in most cases.
